//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogTable
    {
        public blogTable()
        {
            this.blogDetailImage = new HashSet<blogDetailImage>();
            this.commentTable = new HashSet<commentTable>();
        }
    
        public System.Guid blogID { get; set; }
        public string blogTitle { get; set; }
        public string blogContent { get; set; }
        public Nullable<int> blogCategory { get; set; }
        public Nullable<int> blogType { get; set; }
        public Nullable<System.DateTime> blogDateTime { get; set; }
        public string blogImageCover { get; set; }
    
        public virtual ICollection<blogDetailImage> blogDetailImage { get; set; }
        public virtual categoryTable categoryTable { get; set; }
        public virtual typeTable typeTable { get; set; }
        public virtual ICollection<commentTable> commentTable { get; set; }
    }
}
