//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogDetailImage
    {
        public System.Guid blogImageID { get; set; }
        public string blogImagePath { get; set; }
        public Nullable<System.Guid> blogID { get; set; }
    
        public virtual blogTable blogTable { get; set; }
    }
}
