//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryTable
    {
        public categoryTable()
        {
            this.blogTable = new HashSet<blogTable>();
        }
    
        public int categoryID { get; set; }
        public string categoryName { get; set; }
    
        public virtual ICollection<blogTable> blogTable { get; set; }
    }
}
