//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentTable
    {
        public int commentID { get; set; }
        public string commentName { get; set; }
        public string commentEmail { get; set; }
        public string commentContent { get; set; }
        public Nullable<System.Guid> commentBlogID { get; set; }
    
        public virtual blogTable blogTable { get; set; }
    }
}
