//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Entity_.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFblogEntities : DbContext
    {
        public EFblogEntities()
            : base("name=EFblogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adminTable> adminTable { get; set; }
        public DbSet<blogDetailImage> blogDetailImage { get; set; }
        public DbSet<blogTable> blogTable { get; set; }
        public DbSet<categoryTable> categoryTable { get; set; }
        public DbSet<commentTable> commentTable { get; set; }
        public DbSet<typeTable> typeTable { get; set; }
    }
}
